# Generated by Django 3.1.3 on 2020-11-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201116_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='acting_credits', through='core.Role', to='core.Person'),
        ),
        # migrations.AlterField(
        #     model_name='movie',
        #     name='writers',
        #     field=models.ManyToManyField(blank=True, related_name='writing_credits', to='core.Person'),
        # ),
        migrations.RemoveField(
            model_name='movie',
            name='writers',
        ),
        migrations.AddField(
            model_name='movie',
            name='writers',
            field=models.ManyToManyField(blank=True, related_name='writing_credits', to='core.Person'),
        ),
    ]
