# Generated by Django 3.1.3 on 2020-11-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201117_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'UPVOTE'), (-1, 'DOWNVOTE')]),
        ),
    ]
